### ISSUE TITLE
Building icommands on i386 machine

### ISSUE THREAD

**Issue by khaledsalim** [irods/irods_client_icommands#10]
Dear all,

I am currently in the process of building the `irods-icommands` package on our i386 machines, we currently have around 640 i386 machine in our web archive cluster. I was wondering where I can find the `irods-dev` and `irods-runtime` source code to build the packages on our i386 systems. I have checked the irods repository and found the i386 packages empty.

Thank you in advance for your help.

**Comment by kellerb** [comment]
The `irods-dev` and `irods-runtime` packages are produced by the "main" repository, https://github.com/irods/irods.

**Comment by khaledsalim** [comment]
Thank you @kellerb, I will try to build the main `irods` first then.
