### ISSUE TITLE
Unable to read  irule input arguments in rule

### ISSUE THREAD

**Issue by misterbass** [irods/irods_client_icommands#11]
Since I upgrated to 4.2.0, I am facing following error:

- The  input line in the .r rule file specifies arguments as following 
`INPUT *filePath=$, *fileSize=$, *mainResource=$`

- and the rule is called according to irule's help page:
`irule -s -F customPut.r *filePath=/my/path *fileSize=3125 *mainResource=myResc`

Still that, supplied values are not available during execution 
```
status = -1211000 RE_UNABLE_TO_READ_LOCAL_VAR
Level 0: DEBUG: error: unable to read local variable *filePath
line 2, col 20
```

**Comment by trel** [comment]
We have duplicated this behavior - and it is a regression.  We'll get it fixed.

**Comment by tledoux** [comment]
+1
This is a real blocker for using 4.2 release.
Any hint or progress on it ?

**Comment by rskarbez** [comment]
Hi all--

We have a fix for this issue, and it's going to be released soon with iRODS
4.2.1.

If you are comfortable/if your use case allows building from source, you
can build the master branch of irods_client_icommands yourself, which
contains the fix.

Best regards,
Rick Skarbez

**Comment by tledoux** [comment]
Thanks for the quick answer. We will look into it ASAP...
