### ISSUE TITLE
Which commit on 4-2-stable should be used to build clients for iRODS 4.2.7?

### ISSUE THREAD

**Issue by kjsanger** [irods/irods_client_icommands#118]
Which commit on the 4-2-stable branch is the correct one to build iRODS client compatible with iRODS 4.2.7? The HEAD doesn't appear to be compatible any more. There are a number of commits that work, but it's not clear which is preferred, or correct.

Please consider tagging 4-2-stable with the corresponding release number. It would be very helpful when reproducing a build.

Thanks.

**Comment by trel** [comment]
We tag releases in this repository...
   https://github.com/irods/irods_client_icommands/releases

**Comment by kjsanger** [comment]
D'oh! Sorry about that - I should have looked more closely.

**Comment by trel** [comment]
Happy to have an answer for one of your emails :)
