### ISSUE TITLE
Create icommand irmdir

### ISSUE THREAD

**Issue by rskarbez** [irods/irods_client_icommands#14]
Functionality would be the same as Unix rmdir.

Requested in irods/irods#3117.

**Comment by trel** [comment]
please cherry-pick to 4-2-stable

**Comment by mcast** [comment]
Thanks for implementing it.  I skimmed [the code](https://github.com/irods/irods/commit/7263e6e5e4a62ff5fc625d4a4d5e3afbbf7cec3c#diff-41ddc64628cd45f42ada5f05c2db9263R62) (possibly misunderstanding it in the process) and wondered, does it give the same safety guarantees as the POSIX equivalent?

1. check the collection is empty - yes.
2. equivalent to `irm -r`, wrapped as `irmdir`

This is fine until,

1. without getting an exclusive lock on the collection,
2. check the collection is empty - yes.
3. some other client sneaks in and writes a file
4. equivalent to `irm -r`, wrapped as `irmdir`
5. disappointment and data loss?

Could you make the safety guarantee, or lack of, explicit in the `irmdir -h` text please?

**Comment by rskarbez** [comment]
Thanks for checking this; I hadn't considered that potential case. I will certainly update the help text, and will look into what it would take to make the equivalent safety guarantees as the POSIX equivalent.
