### ISSUE TITLE
irsync -r stops in a directory where an error occurs

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_client_icommands#21]
I created a directory (test) with files:

file1.txt, file2.txt, file3.txt, file4.txt

In addition to these, I created a symbolic link dne.txt that point to a non-existent file.

When I run irsync -rv /home/jjames/test i:test, I get a USER_INPUT_PATH_ERR due to the invalid symbolic link.  That is good.  However, the other files within /home/jjames/test do not get synced.  Sometimes some of the files will be synced but not all.  In this case none of them did.

Note:  If this is recursive and there are other higher level directories being synced, the irsync will continue on those.  If it is to continue elsewhere it should continue with all files in the current directory as well.

**Comment by trel** [comment]
Fixed as part of https://github.com/irods/irods/issues/3988
