### ISSUE TITLE
irsync -r --link fails on a bad soft link

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_client_icommands#22]
This is related to issue #21.

I created a directory (test) with files:

file1.txt, file2.txt, file3.txt, file4.txt

In addition to these, I created a symbolic link dne.txt that point to a non-existent file.

When I run irsync -rv --link /home/jjames/test i:test, I get a USER_INPUT_PATH_ERR due to the invalid symbolic link.  

This is unexpected since the "--link" option is supposed to ignore soft links.  Other than error itself, this is causing other files to not be synced (see issue #21).

Note:  If the symbolic link is good, the symbolic link file is not added to iRODS so that part works.

**Comment by trel** [comment]
Fixed as part of https://github.com/irods/irods/issues/3988
