### ISSUE TITLE
Install icommands on CentOS 8 (arch: x84_64) and Red Hat 8 (arch: ppc64le)

### ISSUE THREAD

**Issue by fcola000** [irods/irods_client_icommands#259]
Dear all,

we need to install icommands on the login nodes of our HPC clusters:
The login nodes have these OS/architectures:
 - Intel Xeon Platinum 8276-8276L (x84_64) with CentOS 8.3 
 - IBM Power9 AC922 (ppc64le) with Red Hat 8.1
 
We have already seen that there are no rpm packages available for CentOS 8 and RedHat 8.

On x86_64 I have already tried to install icommands inside a singularity container with CentOS 7 and they seem to work correctly. Is there any known issue with using icommands for CentOS 7 on CentOS 8? Is there another way to install icommands on CentOS 8 without containers? 

On ppc64le I wasn't able to build a container with I icommands, there is no rpm available for ppc64le/centos7. Do you have any suggestions?

Best,
    Francesco

**Comment by trel** [comment]
Hi Francesco,

We are targeting CentOS8-compatible builds/releases for iRODS 4.3.0.   I think running CentOS7 releases in a container is your best bet for having a supported install at this time.

I believe the biggest difference / problem with running the currently released iCommands (4.2.x) on CentOS8 is the libssl versioning.  It was hard enough for us to solve, that we... didn't.... for iRODS 4.2.x.

We have not built/released for power9/ppc64le - and do not currently have any plans to do so.  Our members have not asked for that, so we have not prioritized it.  Of course, we are happy to receive pull requests / patches if you have edits that would get things to build there.

Alternatively, you may find that the Python iRODS Client provides the functionality you need:
 - https://github.com/irods/python-irodsclient

**Comment by SwooshyCueb** [comment]
Given that we've been releasing for EL8 for a while, I think this issue can be closed.
(I can't close it myself as I don't have the proper permissions.)

**Comment by alanking** [comment]
Agreed. Closing. Also, fixed permissions for our group in this repository...
