### ISSUE TITLE
build error in rocky with main branch

### ISSUE THREAD

**Issue by peggy0135** [irods/irods_client_icommands#270]
hi @korydraughn 
after finished in irods server
I met another problem, 
error message showed as below, is that matter with something update? or it just not finished yet.
Thank you

error message:
[ 73%] Building CXX object CMakeFiles/imeta.dir/src/imeta.cpp.o
/root/irods_client_icommands/src/imeta.cpp:1000:38: error: no member named 'condInput' in 'modAVUMetadataInp_t'
        addKeyVal(&modAVUMetadataInp.condInput, ADMIN_KW, "");
                   ~~~~~~~~~~~~~~~~~ ^
/root/irods_client_icommands/src/imeta.cpp:1093:38: error: no member named 'condInput' in 'modAVUMetadataInp_t'
        addKeyVal(&modAVUMetadataInp.condInput, ADMIN_KW, "");
                   ~~~~~~~~~~~~~~~~~ ^
2 errors generated.
make[2]: *** [CMakeFiles/imeta.dir/build.make:76: CMakeFiles/imeta.dir/src/imeta.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2191: CMakeFiles/imeta.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by korydraughn** [comment]
the main branch of the irods/irods repo is out of sync with this repo.

the temporary solution is to comment out the two lines mentioned above. specifically, the lines matching:
```c++
addKeyVal(&modAVUMetadataInp.condInput, ADMIN_KW, "");
```

once https://github.com/irods/irods/pull/6156 is merged, you can re-enable/uncomment the lines mentioned above.
