### ISSUE TITLE
Make iRODS commands RPM package relocatable

### ISSUE THREAD

**Issue by carrgilson** [irods/irods_client_icommands#3]
Could the iRODS icommands package be configured to support the relocatable option in the RPM package?

This describes the option:
http://www.rpm.org/max-rpm/ch-rpm-reloc.html

**Comment by kellerb** [comment]
Looks like `CPACK_RPM_PACKAGE_RELOCATABLE` should do it.

**Comment by carrgilson** [comment]
Would there also be a way to do this with the irods-externals and irods-runtime dependencies of the package too?

**Comment by kellerb** [comment]
FYI, for the purposes of dynamic (run-time) linking, the icommands currently locate the shared libraries contained in the irods-externals package by hardcoding the shared libraries' locations into the icommands' [rpath](https://en.wikipedia.org/wiki/Rpath).

If the libraries were moved to another location that is also not included in the list of directories normally checked by the dynamic linker (e.g. moved to somewhere besides `/lib`, `/usr/lib`, or the other directories `ldconfig` has recorded), then there would need to be additional changes made at the OS level to link the icommands against the libraries, e.g. setting `LD_LIBRARY_PATH` or having `ldconfig` add the new directories to its list of directories searched (e.g. by creating an entry in `/etc/ld.so.conf.d/`).

Can you give a brief explanation of how the relocatable packages will be used / what need they are filling? We would like to make using these packages as easy as possible.

**Comment by carrgilson** [comment]
I want to have the ability to house the commands and all dependent libraries within a single directory structure which will likely be a common network location mounted across an array of machines in an HPC cluster.

If a user needs to use the icommands, they run a command which adds the appropriate path to the applicable environment variables.

The requirement exists so that work-flows can be designed to be independent of the operating system and any OS-bundled software libraries.

**Comment by eburgueno** [comment]
We have exactly the same use case at the cluster that I manage. Maybe you could statically link the libraries and provide that as a separate, relocatable RPM?

**Comment by trel** [comment]
closing - please open a new issue if this is not behaving as expected.
