### ISSUE TITLE
iCommands 4.3.0 fails to run with PAM

### ISSUE THREAD

**Issue by Cotagge** [irods/irods_client_icommands#314]
Hello, i've installed icommands on multiple machines and version 4.3.0 fails to run with pam module. 

```console
Error occurred while authenticating user [dvo0012] [PLUGIN_ERROR_MISSING_SHARED_OBJECT: [-]     /usr/include/irods/irods_load_plugin.hpp:157:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const Ts &...) [PluginType = irods::experimental::auth::authentication_base, Ts = <char [14]>] :  status [PLUGIN_ERROR_MISSING_SHARED_OBJECT]  errno [] -- message [shared library does not exist [/usr/lib/irods/plugins/auth/libirods_auth_plugin-pam_client.so]]



] [ec=-1827000] failed with error -1827000 PLUGIN_ERROR_MISSING_SHARED_OBJECT
```
icommands 4.2.7 works correctly. Please can you look at it?

**Comment by korydraughn** [comment]
The configuration value for enabling PAM in 4.3.0 has changed from `"PAM"` to `"pam_password"`.

Here's the diff showing the updated documentation: https://github.com/irods/irods_docs/commit/ee4cf50841a4a0d8a242bd96ba1faf8839e15675#diff-67cbc78e1822a9c2112cbe4554fef2ba808cfe4e5c041612f6299b3f05c20412

**Comment by Cotagge** [comment]
thanks, works
