### ISSUE TITLE
Install iCommands on Rocky Linux 9

### ISSUE THREAD

**Issue by montesmariana** [irods/irods_client_icommands#397]
Hi all,

Would it be possible to create an iCommands distribution for Rocky Linux 9?

Thank you!

**Comment by korydraughn** [comment]
We have support for Rocky Linux 8 today, so we're hoping it is trivial to support Rocky Linux 9.

To get iCommands, we have to compile all the externals packages and the server. @alanking Is currently working on adding support for Ubuntu 22, so this is great timing.

**Comment by alanking** [comment]
I have demonstrated building iCommands packages for Almalinux 9, so we should have support for this in 4.3.1.

**Comment by montesmariana** [comment]
Ok, thank you!
