### ISSUE TITLE
Usage of `get_grid_configuration` and `set_grid_configuration` not clear

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_icommands#418]
We would like to test 4.3.1. And for this, we have a test environment running irods 4.3.1, iCommands 4.3.1(main) on almalinux8.

I wanted to test sub-commands/features done through the commits available for https://github.com/irods/irods/issues/7274. Also I am seeing some documents https://docs.irods.org/4.3.1/system_overview/configuration/#configuring-authentication-in-r_grid_configuration and here https://github.com/irods/irods_client_icommands/blob/main/src/iadmin.cpp#L2672-L2692. However, I dont see how to use these subcommands in `iadmin -h`, they seem not exist.

But if I run these sub commands, I am getting:
```
[irods@dev-u0137480 irods]$ iadmin get_grid_configuration authentication password_max_time
Failed to get grid configuration for namespace [authentication] and option [password_max_time] [ec=-808000]
```

Also R_GRID_CONFIGURATION table (https://github.com/alanking/irods_docs/commit/21fbfd0730574fad458af10d53e27254f176a217#diff-36178197e1823e07e5432ebea993d7e94af368f2b7160359ee4c61b3f8cddcc0R890) doesnt have more than:

```
MySQL [irods]> select * from R_GRID_CONFIGURATION;
+--------------+----------------+---------------------------------------+
| namespace    | option_name    | option_value                          |
+--------------+----------------+---------------------------------------+
| database     | schema_version | 11                                    |
| delay_server | leader         | dev-u0137480.irods.t.icts.kuleuven.be |
| delay_server | successor      |                                       |
+--------------+----------------+---------------------------------------+
3 rows in set (0.001 sec)
```
This repo doesnt have 4.3.1 release for iCommands yet. Am I missing something?

**Comment by alanking** [comment]
We missed adding these subcommands to the list shown by `iadmin -h`. You can view the help text the subcommands by typing `iadmin h get_grid_configuration` or `iadmin h set_grid_configuration`.

We have an issue here regarding the missing subcommands in the help output: https://github.com/irods/irods_docs/issues/232 Sorry about that...

As for the errors you're seeing, the columns in `R_GRID_CONFIGURATION` are not added until you upgrade the server to 4.3.1 (or is freshly installed as 4.3.1) and furthermore will not have any effect until and unless the server is version 4.3.1. Are you saying that the columns were not added to `R_GRID_CONFIGURATION` even though you are running 4.3.1?

**Comment by mstfdkmn** [comment]
Thanks Alan.

> As for the errors you're seeing, the columns in R_GRID_CONFIGURATION are not added until you upgrade the server to 4.3.1 (or is freshly installed as 4.3.1) and furthermore will not have any effect until and unless the server is version 4.3.1. Are you saying that the columns were not added to R_GRID_CONFIGURATION even though you are running 4.3.1?

Yes, actually we are running a build from the last week (but when we compare the commit we didn't see any changes). I guess then better to run the official release for server?

Also will we see a 4.3.1 release in this repo? https://github.com/irods/irods_client_icommands/releases

**Comment by alanking** [comment]
It would certainly be better to test against the official release, yes.

I'm still surprised that the columns were not added, though. This should have been done as part of the database scheme number changing. Is it possible that this server was itself upgraded from an earlier build such that the database scheme number didn't change?

**Comment by alanking** [comment]
Oh, and I defer to @trel regarding releases on GitHub. :)

**Comment by mstfdkmn** [comment]
Closing this because the error/table is because of a missing internal need.

**Comment by trel** [comment]
I forgot to click the 'turn tag into a release' button on GitHub.   iCommands now have a 4.3.1 release.   Thanks!
