### ISSUE TITLE
incomplete iquery syntax hangs

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_icommands#485]
For example these;

```
root@33d6bc1286de:/# iquery
^C
root@33d6bc1286de:/# iquery -z icts
^C
```

In the examples above I would expect it to to return an informative error or the help document. (Like in other iCommands)

**Comment by korydraughn** [comment]
The behavior you describe is expected. `iquery` will read from stdin when the query string is not provided.

From the help text:
> If QUERY_STRING is a hyphen (-) or is empty, input is read from stdin. Input
> taken via stdin will be viewed as the QUERY_STRING to execute. For example:
>
>    echo select COLL_NAME, DATA_NAME | iquery
>
