### ISSUE TITLE
problem irm of a file in nested directory 

### ISSUE THREAD

**Issue by giuppina** [irods/irods_client_icommands#98]
Dear all,
when I try to remove a file in a nested directory with a very long tree name, I obtain the error

ERROR: main: parseCmdLinePath error.  status = -346000 USER_PATH_EXCEEDS_MAX 

I'm using icommand version 4.2.0-1 
How can I solve?

Best regards. Giusy

**Comment by trel** [comment]
Can you share your actual command and output?

And if you have access, the rodsLog from the server that may have more insight into what happened?

**Comment by giuppina** [comment]
Hi Trel, sorry for the delay. 

The command and the output are:
$ irm -rf /<a tree-path made by 44 characters in total>/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities/project_helpers/sources/utilities
 ERROR: main: parseCmdLinePath error.  status = -346000 USER_PATH_EXCEEDS_MAX
Use -h for help.


In the rodsLog nothing is written when I digit the command. 

Best regards. Giusy

**Comment by trel** [comment]
If there is nothing down there (and it's a mistake to be registered this way in the catalog)... can you just recursively remove a path that is a lot shorter?

aka...

```
irm -rf /<a tree-path made by 44 characters in total>/utilities/project_helpers/sources/utilities/project_helpers/sources
```

**Comment by giuppina** [comment]
I am not able to remove recursively a path shorter because of the error:


$ irm -rf  /<a tree-path made by 44 characters in total>/utilities/project_helpers/sources/utilities/project_helpers/

remote addresses: **.*.*.* ERROR: rmUtil: rm error for /<a tree-path made by 44 characters in total>/utilities/project_helpers/sources/utilities/project_helpers, status = -821000 status = -821000 CAT_COLLECTION_NOT_EMPTY

**Comment by giuppina** [comment]
Hi Trel, no suggestion to solve my proble?
Regards. Giusy

**Comment by trel** [comment]
Can you rename the 'too long' path to something shorter.... using `imv`?

We fixed a number of issues like this in 4.2.4 and 4.2.5.   Consider upgrading if you can.

**Comment by giuppina** [comment]
Hi Trel, renaming with "imv" I was able to cancel the data. 
Thanks a lot. I'll upgrade as soon as possible. 
Thanks again. Giusy

**Comment by trel** [comment]
Excellent - closing this issue.
